language: java
jdk:
  - oraclejdk8
sudo: false

services:
  - docker

script: mvn clean package

after_success:
  - docker build -t ricardobaumann/spring_blog_api:latest .
  - docker push ricardobaumann/spring_blog_api:latest